version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: tartua-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tartua

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - tartua-network

  migrate:
    image: migrate/migrate
    container_name: tartua-migrate

    volumes:
      - ./internal/database/migrations:/migrations

    networks:
      - tartua-network

volumes:
  postgres_data:

networks:
  tartua-network: